version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db
