# Generated by Django 3.0.3 on 2020-06-29 16:43

import Screen.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('uuid', models.CharField(default=Screen.models.random_string, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('puzzle', models.URLField(blank=True, verbose_name='Puzzle')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('uuid', models.CharField(default=Screen.models.random_string, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Screen.Checkpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Screen.Team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('team', 'checkpoint'), name='Constraint'),
        ),
    ]
