# Generated by Django 3.0.3 on 2020-06-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Description'),
        ),
    ]
