# Generated by Django 3.0.3 on 2020-06-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0002_checkpoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Description'),
        ),
    ]
