# Generated by Django 3.2.2 on 2021-05-11 09:20

import Screen.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0003_auto_20200629_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('uuid', models.CharField(default=Screen.models.random_string, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Screen.route'),
        ),
        migrations.AddField(
            model_name='team',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Screen.route'),
        ),
    ]
