# Generated by Django 3.0.3 on 2020-06-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0003_auto_20200628_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='uuid',
        ),
    ]
