# Generated by Django 3.0.3 on 2020-06-28 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0004_auto_20200628_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
