# Generated by Django 3.2.2 on 2021-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0004_auto_20210511_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_file',
            field=models.FileField(default=None, upload_to='checkpoint_file'),
            preserve_default=False,
        ),
    ]
