# Generated by Django 3.2.2 on 2021-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0005_checkpoint_checkpoint_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='checkpoint_file',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
