# Generated by Django 3.0.3 on 2020-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0005_auto_20200628_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='checkpoints',
            field=models.ManyToManyField(to='Screen.Checkpoint'),
        ),
    ]
