# Generated by Django 3.2.3 on 2021-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0006_alter_checkpoint_checkpoint_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Description'),
        ),
    ]
