# Generated by Django 3.0.3 on 2020-06-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0006_team_checkpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='checkpoints',
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='puzzle',
            field=models.URLField(blank=True, verbose_name='Puzzle'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Screen.Checkpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Screen.Team')),
            ],
        ),
    ]
