# Generated by Django 3.2.3 on 2021-05-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0007_alter_checkpoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Description'),
        ),
    ]
