# Generated by Django 3.0.3 on 2020-06-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0007_auto_20200629_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('team', 'checkpoint')},
        ),
    ]
