# Generated by Django 3.0.3 on 2020-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0008_auto_20200629_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_visited',
            field=models.DateTimeField(),
        ),
    ]
