# Generated by Django 3.2.3 on 2021-05-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0009_auto_20210522_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='strafkilometers',
            new_name='strafpunten',
        ),
    ]
