# Generated by Django 3.0.3 on 2020-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0009_auto_20200629_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('team', 'checkpoint'), name='Constraint'),
        ),
    ]
