# Generated by Django 3.0.3 on 2020-06-29 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0010_auto_20200629_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
