# Generated by Django 3.0.3 on 2020-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screen', '0012_auto_20200629_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
    ]
